name: cpp-linter
on:
    pull_request:
        branches: [main, master, develop]
        paths:
            [
                "**.c",
                "**.cpp",
                "**.h",
                "**.hpp",
                "**.cxx",
                "**.hxx",
                "**.cc",
                "**.hh",
                "**CMakeLists.txt",
                "meson.build",
                "**.cmake",
            ]
    push:
        branches: [main, master, develop]
        paths:
            [
                "**.c",
                "**.cpp",
                "**.h",
                "**.hpp",
                "**.cxx",
                "**.hxx",
                "**.cc",
                "**.hh",
                "**CMakeLists.txt",
                "meson.build",
                "**.cmake",
            ]

jobs:
    cpp-linter:
        permissions:
            issues: write
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Set up Compilation Database
              run: cmake --preset Debug

            - uses: cpp-linter/cpp-linter-action@v2
              id: linter
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  style: "file" # Use .clang-format config file.
                  tidy-checks: "" # Use .clang-tidy config file.
                  tidy-review: true
                  format-review: true
                  database: "./build/compile_commands.json"
                  thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
