name: test_and_coverage
on:
  pull_request:
    branches: [main, master, develop]
    paths:
      [
        "**.c",
        "**.cpp",
        "**.h",
        "**.hpp",
        "**.cxx",
        "**.hxx",
        "**.cc",
        "**.hh",
        "**CMakeLists.txt",
        "meson.build",
        "**.cmake",
      ]
  push:
    branches: [main, master, develop]
    paths:
      [
        "**.c",
        "**.cpp",
        "**.h",
        "**.hpp",
        "**.cxx",
        "**.hxx",
        "**.cc",
        "**.hh",
        "**CMakeLists.txt",
        "meson.build",
        "**.cmake",
      ]

jobs:
  test_and_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install ninja
        run: sudo apt-get install ninja-build gcovr -y
      - name: CMake Generate
        run: cmake --preset DebugTest
      - name: Build, Run Test and Generate Report
        run: cmake --build --preset DebugTest --target coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          verbose: true
          files: ./build/coverage.xml
        env:
          token: ${{ secrets.CODECOV_TOKEN }}
