name: test_and_coverage
on:
  pull_request:
    branches: [main, master, develop]
    paths:
      [
        "**.c",
        "**.cpp",
        "**.h",
        "**.hpp",
        "**.cxx",
        "**.hxx",
        "**.cc",
        "**.hh",
        "**CMakeLists.txt",
        "meson.build",
        "**.cmake",
      ]
  push:
    branches: [main, master, develop]
    paths:
      [
        "**.c",
        "**.cpp",
        "**.h",
        "**.hpp",
        "**.cxx",
        "**.hxx",
        "**.cc",
        "**.hh",
        "**CMakeLists.txt",
        "meson.build",
        "**.cmake",
      ]

jobs:
  test_and_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install dependencies
        run: sudo apt-get install ninja-build gcovr -y
      - name: GCC and gcovr version
        run: gcc --version && g++ --version && gcovr --version
      - name: CMake Generate
        run: cmake --preset DebugTest
      - name: Build, Run Test and Generate Report
        run: cmake --build --preset DebugTest --target coverage
      - name: Run Tests
        run: ./build/src/test-project_test
      - name: Generate Report
        run: gcovr --xml ./build/coverage.xml --verbose -e build/vcpkg_installed -e '.*main.cpp' -e '.*_test.cpp'
      - name: Print coverage report
        run: cat ./build/coverage.xml
      - name: Print gcno files
        run: ls -la ./build/src/sublibrary/CMakeFiles/sublibrary.dir
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          verbose: true
          files: ./build/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
